urls.py
from django.conf.urls.defaults import *

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
											 url(r'^admin/', include(admin.site.urls)),
											 url(r'', include('viewers.urls')),
)

viewers/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('viewers.views',
											 url(r'^$', 'index'),
											 url(r'^manage-action', 'manage_action'),
											 url(r'^manage', 'manage'),
											 url(r'^verify', 'verify'),
											 url(r'^submit', 'submit')
)

viewers/models.py
from django.db import models
from HTMLParser import HTMLParser

class Viewer(models.Model):
    jtv_handle = models.CharField(max_length=64)
    sc2_name = models.CharField(max_length=32)
    sc2_charcode = models.IntegerField()
    is_verified = models.BooleanField(default=False)
    
    JTV_COOKIE_NAME = '_jtv3_session_id'
    JTV_INITIAL_PAGE = 'http://www.justin.tv/user/login'
    JTV_LOGIN_PAGE = 'http://www.justin.tv/login'
    JTV_SUBS_PAGE = 'http://www.justin.tv/settings?section=purchases&subsection=subscriptions'
    
    def verify(self, password):
        import urllib2, re
        from urllib import urlencode
        
        # get the authenticity token and session id from JTV
        url = Viewer.get_jtv_url(self.JTV_INITIAL_PAGE)
        if url is None:
            return False
        cookie = url.info().getheader('set-cookie')
        html = url.read()
        url.close()
        
        session_id = self.get_value_from_header(cookie, self.JTV_COOKIE_NAME)
        if session_id is None:
            return False
        
        pattern = re.compile('<input(.*)authenticity_token(.*)value=\"(.*)\"(.*)>')
        match = re.search(pattern, html)
        
        if not match:
            return False
        
        auth_token = match.group(3)
        
        # send login request
        req = urllib2.Request(self.JTV_LOGIN_PAGE)
        req.add_header('Cookie', cookie)
        req.add_header('X-Requested-With', 'XMLHttpRequest')
        req.add_header('Referrer', self.JTV_INITIAL_PAGE)
        req.add_header('Accept', 'text/javascript, text/html, application/xml, text/xml, */*')
        data = {
            'authenticity_token':   auth_token,
            'user[login]':          self.jtv_handle,
            'user[password]':       password,
            'commit':               'Sign In'
        }
        
        url = Viewer.get_jtv_url(req, data)
        cookie = url.info().getheader('set-cookie')
        url.close()
        
        cookie = ''.join([cookie, '; ', self.JTV_COOKIE_NAME, session_id])
        req = urllib2.Request(self.JTV_SUBS_PAGE)
        req.add_header('Cookie', cookie)
        url = Viewer.get_jtv_url(req)
        html = url.read()
        url.close()
        
        pattern = re.compile("<table class='subscriptions_table'>(.*)</table>", re.DOTALL)
        match = re.search(pattern, html)
        
        if not match:
            return False
        
        return self.parse_subs(match.group(1))
        
    def parse_subs(self, content):
        import re
        pattern = re.compile('<tr>(.*?)</tr>', re.DOTALL)
        subs = re.split(pattern, content.strip())
        
        if not subs:
            return False

        for i in range(len(subs)):
            print subs[i]
            
        return False
        
    def __unicode__(self):
        return ''.join([self.jtv_handle, ' - ', self.sc2_name, '.', str(self.sc2_charcode)])
        
    @staticmethod
    def get_value_from_header(header_str, key):
        params = header_str.split('; ')
        for i in range(len(params)):
            args = params[i].split('=')
            if args[0] == key:
                return args[1]
        
        return None
        
    @staticmethod
    def get_jtv_url(req, data=None):
        import urllib2
        from urllib import urlencode
        
        try:
            if data is not None:
                data = urlencode(data)
                
            return urllib2.urlopen(req, data)
        except:
            return None

class SubsParser(HTMLParser):
    def __init__(self):
        self.verified = False
        HTMLParser.__init__(self)
        
    def feed(self, data):
        HTMLParser.feed(self, data)
        print data
        
    def handle_starttag(self, tag, attrs):
        if tag == "tr":
            pass
    
class ViewerSubmission(models.Model):
    viewer = models.ForeignKey(Viewer)
    submit_time = models.DecimalField(max_digits=15, decimal_places=3)
    
    def __unicode__(self):
        from time import time
        from decimal import Decimal
        time_ago = Decimal(str(time())) - self.submit_time
        return ''.join([str(time_ago), ' seconds ago'])

viewers/models/Viewer.py
from django.db import models
from django.contrib.auth.models import User
from urllib import urlencode
import urllib2, re

class Viewer(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    jtv_handle = models.CharField(max_length=64, primary_key=True)
    sc2_name = models.CharField(max_length=32)
    sc2_charcode = models.IntegerField()
    is_verified = models.BooleanField(default=False)
    
    JTV_COOKIE_NAME = '_jtv3_session_id'
    JTV_INITIAL_PAGE = 'http://www.justin.tv/user/login'
    JTV_LOGIN_PAGE = 'http://www.justin.tv/login'
    JTV_SUBS_PAGE = 'http://www.justin.tv/settings?section=purchases&subsection=subscriptions'
    
    class Meta:
        app_label = 'viewers'
        permissions = (
            ('enable monobattles', 'Start/Stop monobattle queueing'),
        )
    
    def verify(self, password):
        # get the authenticity token and session id from JTV
        url = Viewer.get_jtv_url(self.JTV_INITIAL_PAGE)
        if url is None:
            return False
        cookie = url.info().getheader('set-cookie')
        html = url.read()
        url.close()
        
        session_id = self.get_value_from_header(cookie, self.JTV_COOKIE_NAME)
        if session_id is None:
            return False
        
        pattern = re.compile('<input(.*)authenticity_token(.*)value=\"(.*)\"(.*)>')
        match = re.search(pattern, html)
        
        if not match:
            return False
        
        auth_token = match.group(3)
        
        # send login request
        req = urllib2.Request(self.JTV_LOGIN_PAGE)
        req.add_header('Cookie', cookie)
        req.add_header('X-Requested-With', 'XMLHttpRequest')
        req.add_header('Referrer', self.JTV_INITIAL_PAGE)
        req.add_header('Accept', 'text/javascript, text/html, application/xml, text/xml, */*')
        data = {
            'authenticity_token':   auth_token,
            'user[login]':          self.jtv_handle,
            'user[password]':       password,
            'commit':               'Sign In'
        }
        
        url = Viewer.get_jtv_url(req, data)
        cookie = url.info().getheader('set-cookie')
        url.close()
        
        cookie = ''.join([cookie, '; ', self.JTV_COOKIE_NAME, session_id])
        req = urllib2.Request(self.JTV_SUBS_PAGE)
        req.add_header('Cookie', cookie)
        url = Viewer.get_jtv_url(req)
        html = url.read()
        url.close()
        
        pattern = re.compile("<table class='subscriptions_table'>(.*)</table>", re.DOTALL)
        match = re.search(pattern, html)
        
        if not match:
            return False
        
        return self.parse_subs(match.group(1))
        
    def parse_subs(self, content):
        pattern = re.compile('<tr>(.*?)</tr>', re.DOTALL)
        subs = re.split(pattern, content.strip())
        
        if not subs:
            return False

        for i in range(len(subs)):
            if 'Day9tv' in subs[i] and "<p class='green'>Active</p>" in subs[i]:
                return True
            
        return False
        
    def __unicode__(self):
        return ''.join([self.jtv_handle, ' - ', self.sc2_name, '.', str(self.sc2_charcode)])
        
    @staticmethod
    def get_value_from_header(header_str, key):
        params = header_str.split('; ')
        for i in range(len(params)):
            args = params[i].split('=')
            if args[0] == key:
                return args[1]
        
        return None
        
    @staticmethod
    def get_jtv_url(req, data=None):
        try:
            if data is not None:
                data = urlencode(data)
                
            return urllib2.urlopen(req, data)
        except:
            return None

viewers/models/ViewerSubmission.py
from time import time
from decimal import Decimal

from django.db import models


class ViewerSubmission(models.Model):
	sc2_name = models.CharField(max_length=64)
	sc2_charcode = models.CharField(max_length=8)
	submit_time = models.DecimalField(max_digits=17, decimal_places=5)

	class Meta:
		app_label = 'viewers'

	def get_time_diff(self):
		return Decimal(str(time())) - self.submit_time

	def __unicode__(self):
		return ''.join([str(self.get_time_diff()), ' seconds ago'])

viewers/views/index.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django import forms

from variables.models import Variable


def index(request):
	params = {}
	if 'jtv_verified' in request.session and request.session['jtv_verified'] == True:
		params['jtv_verified'] = True
	else:
		params['jtv_verified'] = False

	params['verify_form'] = VerifyForm()
	params['submit_form'] = SubmitForm()
	params['monobattles_enabled'] = Variable.get_bool('monobattles_enabled');

	return render_to_response('viewers/index.html',
														params,
														context_instance=RequestContext(request)
	)


class VerifyForm(forms.Form):
	username = forms.CharField(label='justin.tv username', required=True)
	password = forms.CharField(label='justin.tv password', required=True, widget=forms.widgets.PasswordInput)


class SubmitForm(forms.Form):
	sc2name = forms.CharField()
	sc2code = forms.CharField()

viewers/views/manage.py
import json
from time import time

from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponse

from variables.models import Variable
from viewers.models import ViewerSubmission


def manage(request):
	params = {}

	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('/manage')
		else:
			params['error'] = "Invalid username or password"

	if request.user.is_authenticated() and request.user.has_perm('variables.add_variable'):
		template = 'viewers/manage.html'
		params['is_enabled'] = Variable.get_bool('monobattles_enabled')
	else:
		params['login_form'] = AuthenticationForm()
		template = 'viewers/manage_login.html'

	return render_to_response(template,
														params,
														context_instance=RequestContext(request)
	)


def manage_action(request):
	if not request.is_ajax() or not request.method == 'POST':
		return HttpResponse('invalid request to /manage-action')
	elif not request.user.is_authenticated() or not request.user.has_perm('variables.add_variable'):
		return HttpResponse(json.dumps({
			'success': False,
			'message': 'You are not allowed to enable/disable monobattles'
		}))

	if request.POST['action'] == 'enable':
		Variable.set('monobattles_enabled', True)
		Variable.set('monobattles_last_enabled_time', time())
		return HttpResponse(json.dumps({
			'success': True,
			'message': 'Monobattles are ON!'
		}))

	Variable.set('monobattles_enabled', False)
	last_enabled = Variable.get_decimal('monobattles_last_enabled_time', time())
	submissions_query = ViewerSubmission.objects.filter(
		submit_time__gte=last_enabled
	).order_by('submit_time')
	submissions = []
	for s in submissions_query:
		submissions.append({
			'name': s.sc2_name,
			'code': s.sc2_charcode,
			'time': s.__unicode__()
		})

	return HttpResponse(json.dumps({
		'success': True,
		'message': 'Monobattles have been disabled',
		'submissions': submissions
	}))

viewers/views/submit.py
import json
from django.shortcuts import render_to_response
from django.http import HttpResponse
from variables.models import Variable
from viewers.models import ViewerSubmission
from time import time


def submit(request):
	if not request.is_ajax() or not request.method == 'POST':
		return HttpResponse('invalid request to /submit')
	elif not 'jtv_verified' in request.session or request.session['jtv_verified'] != True:
		return HttpResponse(json.dumps({
			'success': False,
			'message': 'You have not verified your JTV account! Please do that before signing up for monobattles!'
		}))
	elif not Variable.get_bool('monobattles_enabled'):
		return HttpResponse(json.dumps({
			'success': False,
			'message': 'Monobattles are currently disabled'
		}))
	elif not request.POST['sc2_name'] or not request.POST['sc2_charcode'] or not request.POST['sc2_charcode'].isdigit():
		return HttpResponse(json.dumps({
			'success': False,
			'message': 'Please fill out your sc2 character name and code'
		}))

	submission = ViewerSubmission(
		sc2_name=request.POST['sc2_name'],
		sc2_charcode=request.POST['sc2_charcode'],
		submit_time=time()
	)
	submission.save()

	return HttpResponse(json.dumps({
		'success': True,
		'message': 'You signed up for monobattles!'
	}))

viewers/views/verify.py
import json
from django.shortcuts import render_to_response
from django.http import HttpResponse
from viewers.classes import Viewer


def verify(request):
	if not request.is_ajax() or not request.method == 'POST':
		return HttpResponse('invalid request to /verify')

	user = Viewer(jtv_handle=request.POST['username'])
	is_verified = user.verify(request.POST['password'])
	request.session['jtv_verified'] = is_verified

	if is_verified:
		response = {
			'success': True,
			'message': 'You are for suresies subscribed to Day9!',
			'username': user.jtv_handle
		}
	else:
		response = {
			'success': False,
			'message': 'Unable to verify JTV credentials. Check your username/password and try again.',
		}

	return HttpResponse(json.dumps(response))

templates/viewers/index.html
{% extends 'page.html' %}

{% block js %}
    <script type='text/javascript'>
        {% if jtv_verified %}
            var is_jtv_verified = true;
        {% else %}
            var is_jtv_verified = false;
        {% endif %}

        {% if monobattles_enabled %}
            var monobattles_enabled = true;
        {% else %}
            var monobattles_enabled = false;
        {% endif %}

        var WEB_SOCKET_DEBUG = false;
        var WEB_SOCKET_SWF_LOCATION = '{{ STATIC_URL }}websocket/WebSocketMain.swf';
    </script>
    <script type='text/javascript' src='{{ STATIC_URL }}websocket/swfobject.js'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}websocket/web_socket.js'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/viewers.js'></script>
{% endblock %}

{% block css %}
    <style>
        #monobattle_status {
            display: none;
            position: fixed;
            top: 0;
            right: 0;
            border: 1px solid black;
            width: 500px;
            padding: 10px;
            text-align: center;
            font-size: 24px;
            font-weight: bold;
            color: white;
        }

        #monobattle_status.enabled, #monobattle_status.disabled {
            display: block;
        }

        #monobattle_status.enabled {
            background: green;
        }

        #monobattle_status.disabled {
            background: red;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="monobattle_status">
        Monobattles are ON
    </div>
    <div id='verify_message'>
        You have been verified using JTV!
    </div>

    <div id='verify_form_container'>
        <h2>Justin.tv login</h2>

        <div id='verify_error' class='error_message'></div>
        <div class='description'>
            We need your justin.tv login info to make sure you are indeed a subscriber to Day9. Don't worry, we don't
            keep this password.
        </div>
        <form action='/verify' id='verify_form'>
            {% csrf_token %}
            <label for='id_username'>username:</label>
            {{ verify_form.username }}
            <label for='id_password'}>password:</label>
            {{ verify_form.password }}
            <input type='submit' value='verify'/>
            <img class='loading_indicator' src='{{ STATIC_URL }}img/ajax-loader.gif'/>
        </form>
    </div>

    <div id='submit_form_container'>
        <h2>Sign up for monobattles!</h2>

        <div id='submit_message'></div>
        <form action='/submit' id='submit_form'>
            {% csrf_token %}
            <label for='id_sc2name'>sc2 name:</label>
            {{ submit_form.sc2name }}
            <label for='id_sc2code'>character code:</label>
            {{ submit_form.sc2code }}
            <input type='submit' value='sign up!'/>
            <img class='loading_indicator' src='{{ STATIC_URL }}img/ajax-loader.gif'/>
        </form>
    </div>
{% endblock %}

templates/viewers/manage.html
{% extends 'page.html' %}

{% block js %}
    <script type='text/javascript'>
        {% if is_enabled %}
            var signups_enabled = true;
        {% else %}
            var signups_enabled = false;
        {% endif %}

        var WEB_SOCKET_DEBUG = false;
        var WEB_SOCKET_SWF_LOCATION = '{{ STATIC_URL }}websocket/WebSocketMain.swf';
    </script>
    <script type='text/javascript' src='{{ STATIC_URL }}websocket/swfobject.js'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}websocket/web_socket.js'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/manage.js'></script>
{% endblock %}

{% block content %}
    Click the button to <span id='next_action'></span> monobattle sign ups
    <button id='action'></button>
    <img id='loading_indicator' src='{{ STATIC_URL }}img/ajax-loader.gif'/>
    <div id='message'></div>
    <div id='monobattle_signups'></div>
{% endblock %}

templates/viewers/manage_login.html
{% extends 'page.html' %}

{% block content %}
    You must log in before you can begin managing monobattles
    {% if error %}
        <div class='error_message'>
            {{ error }}
        </div>
    {% endif %}
    <form action='/manage' method='post'>{% csrf_token %}
        {{ login_form.as_p }}
        <input type='submit' value='login'/>
    </form>
{% endblock %}